# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    service:
        serializer: "fos_rest.serializer.jms"
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: true
    view:
        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/api/auth, prefer_extension: true, fallback_format: json, priorities: [ html ] }
            - { path: ^/docs, prefer_extension: true, fallback_format: json, priorities: [ html ] }
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }

